### ISSUE TITLE
ランキングファイル壊れそう

### ISSUE THREAD

**Issue by Mushus** [HibikineKage/dog#20]
file_put_contents するときの第三引数の LOCK_EX を使ったほうが良さそう。
書き込み中に読み込まれるとファイルが空なってランキングが壊れるから。
欲を言うと読み込みから保存までロック取ったほうがいいと思う。

**Comment by Mushus** [comment]
外出しててすぐ直せなさそうなのでスマホから報告まで

**Comment by HibikineKage** [comment]
Thanks! ありがたみです

**Comment by HibikineKage** [comment]
@Mushus 応急処置しておきました

**Comment by Mushus** [comment]
SQLiteになったからスレッドセーフになったと思うので閉じ

**Comment by HibikineKage** [comment]
ありがとうございますー
